### ISSUE TITLE
[Feature Request] PixelDrain API

### ISSUE THREAD

**Issue by talha-muneer** [breakdowns/slam-mirrorbot#100]
Hi there, I was wondering if you can add this API to your bot, this is an amazing platform for sharing stuff and I would really appreciate if you can add it. For you I think it will be pretty straightforward considering how you added zippyshare and mediafire.

https://pixeldrain.com/api

please have a look.

**Comment by agamya-samuel** [comment]
@talha-muneer LOL
it takes 1 min to code api for pixel drain, you can't eve do that 😂

**Comment by talha-muneer** [comment]
If you are that good then do it and make a pull request please. 🙂

**Comment by sravantony2** [comment]
@talha-muneer hey bruh
Can I get your telegram username, you are very familiar to me 

I guess you know me

**Comment by sravantony2** [comment]
https://github.com/agamya-samuel/slam-mirrorbot/commit/604a9ed492c7bc93ff2597e74c47b5b4b87f8119

Updated with https://pixeldrain.com/api
Have a look 
@talha-muneer @agamya-samuel
