### ISSUE TITLE
Token expired Problem

### ISSUE THREAD

**Issue by BlackBox-cmd** [breakdowns/slam-mirrorbot#105]
Bot Log
app[worker.1]: Exception in thread Thread-6:

 app[worker.1]: Traceback (most recent call last):

 app[worker.1]:   File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner

 app[worker.1]:     self.run()

 app[worker.1]:   File "/usr/lib/python3.8/threading.py", line 870, in run

 app[worker.1]:     self._target(*self._args, **self._kwargs)

 app[worker.1]:   File "/usr/src/app/bot/modules/mirror.py", line 107, in onDownloadComplete

 app[worker.1]:     drive = gdriveTools.GoogleDriveHelper(up_name, self)

 app[worker.1]:   File "/usr/src/app/bot/helper/mirror_utils/upload_utils/gdriveTools.py", line 43, in __init__

 app[worker.1]:     self.__service = self.authorize()

 app[worker.1]:   File "/usr/src/app/bot/helper/mirror_utils/upload_utils/gdriveTools.py", line 452, in authorize

 app[worker.1]:     credentials.refresh(Request())

 app[worker.1]:   File "/usr/local/lib/python3.8/dist-packages/google/oauth2/credentials.py", line 228, in refresh

 app[worker.1]:     ) = reauth.refresh_grant(

 app[worker.1]:   File "/usr/local/lib/python3.8/dist-packages/google/oauth2/reauth.py", line 338, in refresh_grant

app[worker.1]:     _client._handle_error_response(response_data)

app[worker.1]:   File "/usr/local/lib/python3.8/dist-packages/google/oauth2/_client.py", line 60, in _handle_error_response

 app[worker.1]:     raise exceptions.RefreshError(error_details, response_data)

 app[worker.1]: google.auth.exceptions.RefreshError: ('invalid_grant: Token has been expired or revoked.', {'error': 'invalid_grant', 'error_description': 'Token has been expired or revoked.'})

**Comment by breakdowns** [comment]
We not support for moddified repo. We only support for fork of breakdowns/slam-mirrorbot.
