### ISSUE TITLE
Feature Request.

### ISSUE THREAD

**Issue by hackevil** [breakdowns/slam-mirrorbot#110]
Hey please add support for dynamic config, by dyanamic means that the user will be able to change the config.env var on the go from the bot itself.

for reference please visit these repo.
https://github.com/priiiiyo/priiiiyo-mirror-bot
https://github.com/reaitten/tgchizu

**Comment by breakdowns** [comment]
That kangger version btw. Original source if from https://github.com/ksssomesh12/tg-mirror-bot
