### ISSUE TITLE
Unable to download some telegram files.

### ISSUE THREAD

**Issue by hackevil** [breakdowns/slam-mirrorbot#115]
Hey i am unable to mirror some telegram file to drive. plz look at it.

log: https://del.dog/olicuhycyf.txt

![](https://telegra.ph/file/2b6d41fa35985dc6d8a76.png)

**Comment by breakdowns** [comment]
In group? Did u make bot as admin?

**Comment by breakdowns** [comment]
Coz bot need admin permission for full worl in group.
