### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by reaPeR1010** [breakdowns/slam-mirrorbot#126]
Is there any easy way to update it other than to re deploy again

**Comment by IshanAvasthi** [comment]
@reaPeR1010 Don't be stupid and ask things here.
There is a separate chat group.
Please don't spam our emails.
Because we are watching this repository.

**ISSUE SECTION SHOULD BE USED FOR ISSUES AND FEATURE REQUESTS ONLY**

SUPPORT GROUP []()https://t.me/SlamMirrorSupport

Have a nice day 🙏

**Comment by breakdowns** [comment]
Join support group and check notes
