### ISSUE TITLE
getting error on heroku

### ISSUE THREAD

**Issue by askfriends** [breakdowns/slam-mirrorbot#139]
i have deployed to heroku but getting error in logs and bot is not responding.
i am attaching logs file.
[slam-mirrorbot-logs-1623014675306.txt](https://github.com/breakdowns/slam-mirrorbot/files/6604949/slam-mirrorbot-logs-1623014675306.txt)

**Comment by breakdowns** [comment]
What do you fill in **MAX_TORRENT_SIZE** & **ENABLE_FILESIZE_LIMIT** ?

**Comment by breakdowns** [comment]
Ok so, ig its fixed.
