### ISSUE TITLE
Feature request for mediainfo module

### ISSUE THREAD

**Issue by Vaibhav-08** [breakdowns/slam-mirrorbot#144]
Is it possible to add the same functionality for Links as well (i.e. Index Link or GDrive Shared Links).

Same is available in @MediaInfoHEXbot. I can't find anywhere the code but it is available there. If you can check please.

**Comment by xd003** [comment]
+1 for this request
It would be super helpful to have it

I just checked that bot works really quickly and efficiently

**Comment by Vaibhav-08** [comment]
> +1 for this request
> It would be super helpful to have it
> 
> I just checked that bot works really quickly and efficiently

True that's very cool to have info from URL in addition to TG files.

**Comment by prono69** [comment]
Bruhhhhhhhh

**Comment by prono69** [comment]
It's already added :unamused:

**Comment by prono69** [comment]
Close the issue

**Comment by xd003** [comment]
> Close the issue

First of all write everything under single message , why spamming by writing 3 messages unnecessarily
Secondly read & check properly before saying , mediainfo currently only works for telegram files not on URL's

**Comment by askfriends** [comment]
+1

**Comment by mukulsharma06175** [comment]
> > Close the issue
> 
> First of all write everything under single message , why spamming by writing 3 messages unnecessarily
> 
> Secondly read & check properly before saying , mediainfo currently only works for telegram files not on URL's

+1
