### ISSUE TITLE
NOT WORKING

### ISSUE THREAD

**Issue by MaxxRider** [breakdowns/slam-mirrorbot#149]
Duplicate Clone feature not working

**Comment by breakdowns** [comment]
> Duplicate Clone feature not working

![Screenshot_20210609-161754409](https://user-images.githubusercontent.com/71178188/121328279-64216e80-c93e-11eb-97e7-8674e391b7c4.jpg)
Working fine here

**Comment by MaxxRider** [comment]
I Deployed 1 hour ago
why not working for me ? 🤔
