### ISSUE TITLE
PLEASE DELETE YOUR REPO

### ISSUE THREAD

**Issue by tomyprs** [breakdowns/slam-mirrorbot#159]
Your repo is not human readable.
Too many bugs, and duplicated code, does your code not refer to pylint? ,

``Am I too stupid``

Sorry in advance, it's not that I don't appreciate it, but at least, fix the existing problem, before adding features ...

**Comment by anasty17** [comment]
U can easy ignore this repo ... without telling us that u r shit

**Comment by anasty17** [comment]
Yah simply pass don't say shit like ur face

**Comment by breakdowns** [comment]
Saya tidak pernah merekomendasikan/memaksa Anda untuk menggunakan repo ini, jadi silahkan gunakan repo lain. Thanks
