### ISSUE TITLE
adding Qbittorrent in addition to Aria2 to avoid client ban .

### ISSUE THREAD

**Issue by ronin08** [breakdowns/slam-mirrorbot#174]
Some private trackers have banned aria2 . Even with changed user-agent and peer-id they can identify it by the actual handshake method of aria2 . 
By implementing actual qbittorrent via python module , it will be same as downloading from qbittorrent without any hiccups .

Even a project namely : tortoolkit ( https://github.com/yash-dk/TorToolkit-Telegram ) uses Qbittorrent for every torrent download and it's fast AF ! 
Here is the code : (  https://github.com/yash-dk/TorToolkit-Telegram/blob/master/tortoolkit/functions/QBittorrentWrap.py )

Please have a look into this .

**Comment by breakdowns** [comment]
Then use ttk dont use slam.
