### ISSUE TITLE
No worker is declared.

### ISSUE THREAD

**Issue by oneironaut2209** [breakdowns/slam-mirrorbot#176]
Scaling dynos... !
 !    Couldn't find that process type (worker).

getting this error while deploying through heroku-cli

**Comment by breakdowns** [comment]
heroku ps:scale worker=0 -a appname
heroku ps:scale worker=1 -a appname

**Comment by oneironaut2209** [comment]
this is what gets error

**Comment by anasty17** [comment]
Remove .gitignore file and hit git add . 
Then git commit -m "any" 
Then continue 
Make sure heroku.yml file exists

**Comment by oneironaut2209** [comment]
> Remove .gitignore file and hit git add .
> Then git commit -m "any"
> Then continue
> Make sure heroku.yml file exists

Same issue again
I also did "heroku git:remote -a appname"

**Comment by anasty17** [comment]
https://t.me/SlamMirrorSupport contact me here
