### ISSUE TITLE
fix mega link issue

### ISSUE THREAD

**Issue by crazy-racer** [breakdowns/slam-mirrorbot#181]
Dear admin your repo mega.zn not mirror
![IMG_20210616_120400](https://user-images.githubusercontent.com/69627019/122171151-05f40e80-ce9d-11eb-936c-261001561c61.jpg)

**Comment by breakdowns** [comment]
1. Check your link.
2. Send your link.
3. Free Mega account limit 4-5GB transfer per 6 hours.

**Comment by crazy-racer** [comment]
add morror hotstar link

**Comment by breakdowns** [comment]
Use EU server.
