### ISSUE TITLE
How to solve No such file or directory: 'accounts/0.json'

### ISSUE THREAD

**Issue by kanyevelvet** [breakdowns/slam-mirrorbot#187]
How to solve [No such file or directory:'accounts/0.json']
i already upload accounts folder and many json files. also the SA is already add on the Shared Drive.
and set up Config Vars [USE_SERVICE_ACCOUNTS, True]  complete in heroku.
the normal setting works fine without SA.

![image](https://user-images.githubusercontent.com/70871779/122309041-89b70500-cf48-11eb-8e76-23312503db08.png)

**Comment by breakdowns** [comment]
Go to support group and check notes.
