### ISSUE TITLE
fix bug rclone and mega 

### ISSUE THREAD

**Issue by crazy-racer** [breakdowns/slam-mirrorbot#195]
Dear admin rclone fix bug.. fill in  config env clone dual "True" and Sam mega
![IMG_20210617_150447](https://user-images.githubusercontent.com/69627019/122373356-09f85d00-cf7f-11eb-89b4-8a0a5be0ef42.jpg)

**Comment by breakdowns** [comment]
Pls report in support group.

**Comment by crazy-racer** [comment]
but support group not sms reply and  ban
