### ISSUE TITLE
How to add optional vars in config after recent update?

### ISSUE THREAD

**Issue by askfriends** [breakdowns/slam-mirrorbot#224]
Hello;
after recent update there is no config.env file in the repo and its replaced by bot command itself but there is no optional vars available in the bot.
So how can we set optional vars like mega api or some other vars?

And you havnt updated/added new commands in the command list because you have added some new commands in the bot update.

**Comment by breakdowns** [comment]
Just update & u will know how to do.

Also pls join support group & stop make issue.
