### ISSUE TITLE
Mediainfo

### ISSUE THREAD

**Issue by Gautampro1834** [breakdowns/slam-mirrorbot#24]
Add mediainfo module 
For getting mediainfo of a telegram file or a drive file through drive shareable link 
And post results on telegraph with button

You can get some help from this : https://github.com/code-rgb/USERGE-X/blob/alpha/userge/plugins/utils/mediainfo.py

**Comment by breakdowns** [comment]
![Uploading Screenshot_20210312-034518.jpg…]()
You maen this?

**Comment by breakdowns** [comment]
![Screenshot_20210312-034518](https://user-images.githubusercontent.com/71178188/110852888-7e1ec700-82e5-11eb-8fb3-52c8d44c5701.jpg)
You maen this?

**Comment by Gautampro1834** [comment]
No these are search results from drive

I'm talking about mediainfo of a video file
Like this 👇
https://telegra.ph/pyrogramtypesVideo-03-10-2

**Comment by breakdowns** [comment]
> No these are search results from drive
> 
> I'm talking about mediainfo of a video file
> Like this 👇
> https://telegra.ph/pyrogramtypesVideo-03-10-2

Will try, but not now, cuz busy

**Comment by breakdowns** [comment]
Added

**Comment by Vaibhav-08** [comment]
This module works great for Telegram Files but it does not work for Links (i.e. Index Link or GDrive Shared Links). Can you please check?
