### ISSUE TITLE
[Feature Request] Ability to multiple URLs using /watch command

### ISSUE THREAD

**Issue by theDemon92** [breakdowns/slam-mirrorbot#245]
Hi devs,

I request you to add the functionality of downloading multiple urls separated by comma using /watch command 

Example : 

/watch https://www.youtube.com/watch?v=G8wxsGl-rMA,https://www.twitch.tv/jnxisee/video/1067852522 and so on

**Comment by anasty17** [comment]
Maybe soon bro 👍

**Comment by theDemon92** [comment]
> Maybe soon bro 👍, not for watch only

thanks br
