### ISSUE TITLE
#Help Broiii

### ISSUE THREAD

**Issue by Clinton-Abraham** [breakdowns/slam-mirrorbot#258]
![IMG_20210705_201626](https://user-images.githubusercontent.com/70835540/124488827-ee3de500-ddcd-11eb-8ffb-597ee446820e.jpg)
![Uploading Screenshot_2021-07-05-20-13-58-427_com.brave.browser.jpg…]()

**Comment by Clinton-Abraham** [comment]
![Screenshot_2021-07-05-20-13-58-427_com brave browser](https://user-images.githubusercontent.com/70835540/124488961-162d4880-ddce-11eb-88a0-48614ab99908.jpg)

**Comment by breakdowns** [comment]
Your database, btw no need make issue like this, you can join to support group.
