### ISSUE TITLE
cancel error

### ISSUE THREAD

**Issue by rezcoco** [breakdowns/slam-mirrorbot#28]
/cancel command error

**Comment by breakdowns** [comment]
![Screenshot_20210318-164647~2](https://user-images.githubusercontent.com/71178188/111606289-a3da2d80-8809-11eb-8b30-c457f4f6698b.jpg)
Use /cancel (gid)

**Comment by rezcoco** [comment]
Done thanks, anyway did you know how to solve MEGA over quota limit
or it needs MEGA Premium Account ?

**Comment by breakdowns** [comment]
> Done thanks, anyway did you know how to solve MEGA over quota limit
> or it needs MEGA Premium Account ?

Yes, or just wait for tomorrow
