### ISSUE TITLE
Is it possible to integrate Upload to Telegram module?

### ISSUE THREAD

**Issue by venom4525** [breakdowns/slam-mirrorbot#29]
Can it be added to the bot such that the files larger than 2 GB would be splitted into parts and then uploaded to authorized group with mirror to telegram command?

Module reference:
https://github.com/gautamajay52/TorrentLeech-Gdrive/tree/master/tobrot/helper_funcs

**Comment by theRay1s** [comment]
Why u want upload to telegram upload in mirror bot 

It's better this way
