### ISSUE TITLE
Crashed

### ISSUE THREAD

**Issue by saurab6** [breakdowns/slam-mirrorbot#327]
It's crashing because the sa and token pickle is not being loaded at the beginning from index url

**Comment by saurab6** [comment]
[slambot6-logs-1629104958241.txt](https://github.com/breakdowns/slam-mirrorbot/files/6991076/slambot6-logs-1629104958241.txt)
 Above are the logs

**Comment by ronin08** [comment]
can confirm , it is crashing showing same error as in the above attached logs by @saurab6 after the few last update . The reason should be : @anasty17 removed extracting accounts.zip and loading token.pickle from their respective URL  at the start ( by editing start.sh) . 

Any explanation would be appreciated .

**Comment by breakdowns** [comment]
@ronin08 Read this https://t.me/SlamMirrorSupport/69793

**Comment by ronin08** [comment]
> @ronin08 Read this https://t.me/SlamMirrorSupport/69793

it is alright , I checked it twice . It was working fine before yesterday's upadate .

**Comment by anasty17** [comment]
> > @ronin08 Read this https://t.me/SlamMirrorSupport/69793
> 
> it is alright , I checked it twice . It was working fine before yesterday's upadate .

Zip the accounts folder not the json files .... check readme changes

**Comment by ronin08** [comment]
> > > @ronin08 Read this https://t.me/SlamMirrorSupport/69793
> > 
> > 
> > it is alright , I checked it twice . It was working fine before yesterday's upadate .
> 
> Zip the accounts folder not the json files .... check readme changes

OOPS ! it's other way round :) thanks for clearing . It's fine now 😊

**Comment by saurab6** [comment]
Idk what I did wrong but still getting error even after zipping the accounts folder
[slambot6-logs-1629108252144.txt](https://github.com/breakdowns/slam-mirrorbot/files/6991456/slambot6-logs-1629108252144.txt)
