### ISSUE TITLE
Bot going to sleep

### ISSUE THREAD

**Issue by aashath20** [breakdowns/slam-mirrorbot#328]
Bot always going to sleep how to fix it

**Comment by ronin08** [comment]
put question properly with attached logs to get fast solution

**Comment by aashath20** [comment]
> put question properly with attached logs to get fast solution

2021-08-16T07:58:41.290955+00:00 heroku[web.1]: Idling
2021-08-16T07:58:41.294914+00:00 heroku[web.1]: State changed from up to down
2021-08-16T07:58:43.369904+00:00 heroku[web.1]: Stopping all processes with SIGTERM
2021-08-16T07:58:43.503095+00:00 heroku[web.1]: Process exited with status 143

**Comment by ronin08** [comment]
have you filled 'BASE_URL_OF_BOT' config ? This needs to be filled with link of web app of the deployed server ( for heroku it will be like this : https://yourappname.herokuapp.com)

**Comment by aashath20** [comment]
> have you filled 'BASE_URL_OF_BOT' config ? This needs to be filled with link of web app of the deployed server ( for heroku it will be like this : https://yourappname.herokuapp.com)

Yah Bro

**Comment by breakdowns** [comment]
Make sure your repo up-to-date, also read README.md Correctly, is already in README.md
