### ISSUE TITLE
[Feature Upgrade Request] Migrate from Mega SDK python binding to MegaSdkRestClient

### ISSUE THREAD

**Issue by rokibhasansagar** [breakdowns/slam-mirrorbot#334]
[Mega SDK](https://github.com/meganz/sdk) python binding needs too much space in the bot environment. The SDK repository is currently needed for the python package to work.
But for using [MegaSdkRestClient](https://github.com/viswanathbalusu/megasdkrest), there is no need of the SDK to be built from scratch. Just a few dependency packages are needed on runtime.

Currently TorToolkit, MirrorX and some other bots are using MegaSdkRestClient.
Even lzzy12's python-aria-mirror-bot is also using MegaSdkRestClient instead of SDK python binding.

Migrating to MegaSdkRestClient will make the bot environment slimer than current system, thus making it faster to deploy.

**Comment by breakdowns** [comment]
Megasdkrest can't handle many Mega mirror, only can mirror one by one

**Comment by anasty17** [comment]
> [Mega SDK](https://github.com/meganz/sdk) python binding needs too much space in the bot environment. The SDK repository is currently needed for the python package to work.
> But for using [MegaSdkRestClient](https://github.com/viswanathbalusu/megasdkrest), there is no need of the SDK to be built from scratch. Just a few dependency packages are needed on runtime.
> 
> Currently TorToolkit, MirrorX and some other bots are using MegaSdkRestClient.
> Even lzzy12's python-aria-mirror-bot is also using MegaSdkRestClient instead of SDK python binding.
> 
> Migrating to MegaSdkRestClient will make the bot environment slimer than current system, thus making it faster to deploy.

Deploying take 3 mins ! U deploy everyday? It's not slimer it's shit only one or two mega tasks can run depending on ur memory
