### ISSUE TITLE
config

### ISSUE THREAD

**Issue by yuno74** [breakdowns/slam-mirrorbot#54]
can you make config works like this

# ENTER BOT TOKEN (Get your BOT_TOKEN by talking to @botfather)
BOT_TOKEN = ""
GDRIVE_FOLDER_ID = "root"
OWNER_ID =
DOWNLOAD_DIR = ""
DOWNLOAD_STATUS_UPDATE_INTERVAL = 5
AUTO_DELETE_MESSAGE_DURATION = -1
IS_TEAM_DRIVE = ""
TELEGRAM_API = 
TELEGRAM_HASH = ""

# Optional config
AUTHORIZED_CHATS = ""
USE_SERVICE_ACCOUNTS = ""
INDEX_URL = ""
UPTOBOX_TOKEN = ""
MEGA_API_KEY = ""
MEGA_EMAIL_ID = ""
MEGA_PASSWORD = ""  
BLOCK_MEGA_FOLDER = ""
BLOCK_MEGA_LINKS = ""
STOP_DUPLICATE_MIRROR = ""
SHORTENER = ""
SHORTENER_API = ""

# Change ENABLE_FILESIZE_LIMIT = True if you want to use MAX_TORRENT_SIZE
ENABLE_FILESIZE_LIMIT = True
MAX_TORRENT_SIZE = 

# For VPS or Any Server with limit transfer or Bandwidth
BANDWIDTH_LIMIT = 

# Add more buttons (two buttons are already added of file link and index link, you can add extra buttons too, these are optional)
# If you don't know what are below entries, simply leave them, Don't fill anything in them.
BUTTON_THREE_NAME = ""
BUTTON_THREE_URL = ""
BUTTON_FOUR_NAME = ""
BUTTON_FOUR_URL = ""
BUTTON_FIVE_NAME = ""
BUTTON_FIVE_URL = ""

# Command edit
START_COMMANDS = 
MIRROR_COMMANDS = 
UNZIP_MIRROR_COMMANDS = 
TAR_MIRROR_COMMANDS = 
CANCEL_MIRROR_COMMANDS = 
CANCEL_MIRROR_ALL_COMMANDS = 
LIST_COMMANDS = 
STATUS_COMMANDS = 
AUTH_COMMANDS = 
UNAUTH_COMMANDS = 
AUTH_LIST_COMMANDS = 
PING_COMMANDS = 
RESTART_COMMANDS = 
INFO_COMMANDS = 
HELP_COMMANDS = 
LOG_COMMANDS = 
SPEED_TEST_COMMANDS = 
CLONE_COMMANDS = 
YT_COMMANDS = 
TAR_YT_COMMANDS = 
DELETE_COMMANDS = 

# Anime module command edit
ANIME_SEARCH_COMMANDS = 
CHARACTER_SEARCH_COMMANDS = 
MANGA_SEARCH_COMMANDS = 
WEEBHELP_COMMANDS = 

# Torrent command search from nyaa and sukebei edit
NYAA_TORRENT_COMMANDS = 
SUKEBEI_TORRENT_COMMANDS =

# Anime photo command edit link
ANIME_PHOTO_URL = 

# Torrent search photo edit link
TORRENT_PHOTO_LINK = 

# Start photo link edit
START_PHOTO_LINK =

**Comment by yuno74** [comment]
so user only need edit in config

**Comment by IshanAvasthi** [comment]
![image](https://user-images.githubusercontent.com/78077297/116695949-e41ef500-a9de-11eb-9688-1e9fb9944c9c.png)
is this edit in var correct?

**Comment by agamya-samuel** [comment]
> ![image](https://user-images.githubusercontent.com/78077297/116695949-e41ef500-a9de-11eb-9688-1e9fb9944c9c.png)
> is this edit in var correct?

yes, absolutely correct
