### ISSUE TITLE
Some torrents won't work on this repo but will work instantly on other.

### ISSUE THREAD

**Issue by talha-muneer** [breakdowns/slam-mirrorbot#77]
Hi there, I am facing an issue such that when I put something to download using the bot created from you repo, it doesn't start download at all saying its a dead torrent but when I put same torrent in bot from another repo, It works without any problem. Please look into it.

**Comment by breakdowns** [comment]
Remove --bt-stop-timeout=1200 in aria.sh.
https://github.com/breakdowns/slam-mirrorbot/blob/5894b540d87ae5f5ccae8e83828d119de2774a86/aria.sh#L7

**Comment by talha-muneer** [comment]
Thanks A Lot. Will Do So And Get Back To You
