### ISSUE TITLE
Error R14 (Memory quota exceeded)

### ISSUE THREAD

**Issue by agamya-samuel** [breakdowns/slam-mirrorbot#80]
When deployed on Heroku, Bots work for 1-2 hours then start thorowing this error

2021-05-06T08:05:11.949031+00:00 heroku[worker.1]: Process running mem=1013M(197.9%)
2021-05-06T08:05:11.986383+00:00 heroku[worker.1]: Error R14 (Memory quota exceeded)
2021-05-06T08:05:33.560928+00:00 heroku[worker.1]: Process running mem=1031M(201.6%)
2021-05-06T08:05:33.565341+00:00 heroku[worker.1]: Error R15 (Memory quota vastly exceeded)
2021-05-06T08:05:33.567105+00:00 heroku[worker.1]: Stopping process with SIGKILL
2021-05-06T08:05:33.741992+00:00 heroku[worker.1]: Process exited with status 137
2021-05-06T08:05:33.806805+00:00 heroku[worker.1]: State changed from up to crashed

After researchin g a bit, I found this article [https://devcenter.heroku.com/articles/ruby-memory-use](url) that said this :-

If you’re getting R14 - Memory quota exceeded errors, it means your application is using swap memory. Swap uses the disk to store memory instead of RAM. Disk speed is significantly slower than RAM, so page access time is greatly increased. This leads to a significant degradation in application performance. An application that is swapping will be much slower than one that is not. No one wants a slow application, so getting rid of R14 Memory quota exceeded errors on your application is very important.

I am runnig it on Free dynos.

Error Log.
[https://del.dog/vudynovefu.txt](url)

![Screenshot (74)](https://user-images.githubusercontent.com/48693970/117264637-0ac2ad00-ae71-11eb-9819-023304db2af4.png)

**Comment by reaitten** [comment]
I see I have Error R15 with one of my bots. It happens sometimes when it is overloaded with a excessive amount of downloads. If you only limit it with like 2-3 or even 4 concurrent downloads, it'll still have Error R14, but most of the time, it wouldn't have Error R15, at least for me.

I'm pretty sure this happens to all Mirror Bots, but please do correct me if I am wrong.

**Comment by AmirulAndalib** [comment]
crank down workers and use heroku cc :) simple

**Comment by AmirulAndalib** [comment]
or change region to eu for good

**Comment by agamya-samuel** [comment]
1st, as mentioned by @reaitten,I only I had only 1gb test file downloaded, after which 
 got the R14 error 😂. I was testing the BOTs. Nothing else was downloading.

2nd, I know majority people use USA data centers for the BOT deployment, as it is the default option in Heroku, so I had always used the Europe server for depoyment, due to low load and in generals BOTs respond faster. Did not helped, tried both USA as well as Europe nothing happened, and whats strange is I deployed 3 BOTs and all stooped at once, givin same error R14.

I wanted to know what was causing the error, I wanted to isolate, the reason by which the BOTs kept stopping, so i checked Logs again, it said, Process running mem = 889 MB, I realised that its aking for more than 500 MB RAM, which Hroku gives on its free dynos, so I added my CC, and scaled up the dynos to STANDARD 2x dynos, which cost 50$/month, and which gave 1 GB RAM, and it fixed the problem. (Only Temporarily)
BOT started working again.

![image](https://user-images.githubusercontent.com/48693970/117463067-e64bfb00-af6c-11eb-9cd4-910564690d7f.png)

Only Few Hours(5-6 hours) later I again got the same R14 Error came up,  and this time it was sking for more than 1 GB RAM, I was like WTF Bro, are you kidding me !

2021-05-07T14:32:20.501148+00:00 heroku[worker.1]: Process running mem=1284M(125.5%)
2021-05-07T14:32:20.529874+00:00 heroku[worker.1]: Error R14 (Memory quota exceeded)

![image](https://user-images.githubusercontent.com/48693970/117465238-1dbba700-af6f-11eb-9eb0-7f58ef20c56b.png)

So I scaled up the dynos again to PERFORMANCE-M dynos that comes with 2.5 GB RAM and cost 250$/month, I just wanted to isolate the problem that was causing it. So this was me, expermentng what was the cause of this R14 Error.

![image](https://user-images.githubusercontent.com/48693970/117465669-8c006980-af6f-11eb-9e9f-89d0cb7febfa.png)

Now BOTs are working completely fine with 2.5 GB RAM, and 50 GB of usable storage, YES! reduces from 375 GB to 50 GB onPERMONCE-M dynos and costing me 250$/month

![Screenshot (91)](https://user-images.githubusercontent.com/48693970/117466956-e0581900-af70-11eb-841f-38cb6490f9f4.png)

**Comment by prono69** [comment]
Strange :(

**Comment by agamya-samuel** [comment]
I solved the Issue on My own 😂
Problem was not in Bots, nor in repo, nor in Heroku, problem was in my Mega.nz account.

![image_2021-05-06_13-46-55](https://user-images.githubusercontent.com/48693970/117532445-337bab80-b005-11eb-88b3-9f595e321288.png)

I had arounf 200 TB data in my mega account 😂, so the poor BOTs when were loggin into the mega account, they had to decrypt 200 TB data 😂.
Sorry my bad, issue from my side.
Perhaps it would be great, if author can add this warning in the original repo, it will help other users.

**Comment by AmirulAndalib** [comment]
🤪
