### ISSUE TITLE
Bot randomly generates error 403

### ISSUE THREAD

**Issue by talha-muneer** [breakdowns/slam-mirrorbot#93]
The bot randomly generates error 403 insufficient permission in case of **education drive**. It will copy some folders and other time it will generate error "HttpError 403 when requesting https://www.googleapis.com/drive/v3/files/1VvCaPZ5WsWYUgpGxA8zbYkTeUwksxFr_/permissions?supportsTeamDrives=true&alt=json returned "The user does not have sufficient permissions for this file." 

this happens in case of having some folders inside the torrent/link. As you can see from attached photos. It does copy but not completely. Please refer to the logs for more details. I have successfully upploaded the token.pickle file and it has complete access to the **education drive**.

[log.txt](https://github.com/breakdowns/slam-mirrorbot/files/6489335/log.txt)

![chrome_Oek0S3LXRE](https://user-images.githubusercontent.com/78280937/118400075-85fa3f00-b679-11eb-8bdf-5cdef45b9071.png)

**Comment by rikyuking** [comment]
[If your permissions allow you to use Files: get but not Permissions: list, you have only View Access to a file
You need to be an editor or owner to use Permissions:list](https://stackoverflow.com/questions/61818050/g-suite-drive-api-why-cant-i-get-the-permissions-of-a-specific-file)


[Deprecated use supportsAllDrives instead. (Default: false)](https://developers.google.com/drive/api/v3/reference/permissions/list)
